// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlFormatter
{
    internal sealed partial class Vsix
    {
        public const string Id = "SqlFormatter.70C3AE03-7E78-41F3-8FE0-11BF482F5F69";
        public const string Name = "SQL Formatter for SSMS (preview)";
        public const string Description = @"Adds support for the Format Document command for SQL files. Use Ctrl+K, Ctrl+D to execute the command to format the document. Configure the formatting behavior through options.";
        public const string Language = "en-US";
        public const string Version = "0.0.4";
        public const string Author = "ErikEJ";
        public const string Tags = "sql, tsql, formatter, database";
        public const bool IsPreview = true;
    }
}
