// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlFormatter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string autoloadString = "81883f78-d33e-4fde-8a2c-6318c81d3c60";
        public static Guid autoload = new Guid(autoloadString);

        public const string SqlFormatterString = "370a4d64-9e03-4846-8b00-49fcb57d817e";
        public static Guid SqlFormatter = new Guid(SqlFormatterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FormatSql = 0x0064;
        public const int FormatSqlGroup = 0x0001;
    }
}